version: '3.4'

services:
  productmanagementsystem.server:
    image: ${DOCKER_REGISTRY-}productmanagementsystemserver
    build:
      context: .
      dockerfile: ProductManagementSystem.Server/Dockerfile
    ports:
      - "8081:8081"  # Map port 80 in the container to port 8080 on the host
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"  # Set a strong password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # Adjust port as needed